{% set name = "amazon-sagemaker-sql-magic" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-sagemaker-sql-magic-{{ version }}.tar.gz
  sha256: 9fe939fcd93d857132d7334a8de9c11f2cab74e9176cf7fab0a9a1124bc7fcc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.8
    - pandas
    - ipython
    - sqlparse ==0.4.*
    - amazon-sagemaker-sql-execution >=0.0.7,<1

test:
  imports:
    - amazon_sagemaker_sql_magic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/amazon-sagemaker-sql-magic/
  summary: 'Package which provides sql magic commands for Sagemaker SQL extension'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kumarnzt
    - gogakoreli
    - varun196
    - HariniNarayanan
